[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

description = "Calculate the Unique Numeric Fingerprint for Tabular Data"

classifiers = [
    "Development Status :: 4 - Beta"
]

keywords = [ 
    "data",
    "hash"
]